# Configuración basada en https://docs.travis-ci.com/user/languages/java/
# Lenguaje de programación utilizado
language: java
# Guardar las dependencias de Maven en el directorio .m2 para no descargalar cada vez que se ejecuta un build
cache:
  directories:
    - $HOME/.m2
# Versiones de JDK, en este caso utilizamos 4, las versiones menores no pueden ser inferiores a la 8, 
# puesto que la versión del framework utilizado no lo soporta. 
# Al momento de realizar el proyecto, la última versión estable es la 13
jdk:
- oraclejdk8
- openjdk8

- oraclejdk13
- openjdk13

# Distribución de linux seleccionada del conjunto que proporciona travis, en este caso Ubuntu Trusty 14.04, la distribución más reciente que todavía soporta la JDK 8 de Oracle
dist: trusty
before_install:
# Proporcionar permisos de lectura y escritura dentro de la carpeta mvnw del microservicio vendors_products 
- chmod +x vendors_products/mvnw
script:
# Ejecutar los test del microservicio vendors_products
  - mvn  -B -f vendors_products/pom.xml test